# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hello world
email: jerryzhen11@outlook.com
description: > # this means to ignore newlines until "baseurl:"
 欢乐逗 All-stack 运动 Game =>就是我~
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: jerry
github_username:  jerryzhen11

# Build settings
markdown: kramdown
